version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DEBUG}

  db:
    image: postgres:13
    volumes:
      - bookstore-db-data:/var/lib/postgres/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


volumes:
  bookstore-db-data: